// src/components/PromissoryNotePDF/styles.ts

import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  pageWithoutGuarantor: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 10,
    paddingTop: 10,
  },
  pageWithGuarantor: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 10,
    paddingTop: 12,
  },
  pagareWithoutGuarantor: {
    border: "0.75 solid #2E7D32",
    borderRadius: 4,
    padding: 10,
    marginBottom: 10,
    backgroundColor: "#FFFFFF",
    width: "100%",
    boxShadow: "0 1 2 rgba(0, 0, 0, 0.1)",
  },
  pagareWithGuarantor: {
    border: "0.75 solid #2E7D32",
    borderRadius: 4,
    padding: 10,
    marginBottom: 15,
    backgroundColor: "#FFFFFF",
    width: "100%",
    boxShadow: "0 1 2 rgba(0, 0, 0, 0.1)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F1F8E9",
    color: "#2E7D32",
    padding: 6,
    marginBottom: 6,
    borderRadius: 3,
    border: "0.75 solid #2E7D32",
  },
  headerText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#2E7D32",
  },
  headerRight: {
    flexDirection: "row",
    fontSize: 9,
    alignItems: "center",
  },
  headerRightItem: {
    paddingHorizontal: 5,
    fontWeight: "medium",
  },
  verticalLine: {
    borderLeft: "0.75 solid #2E7D32",
    height: "100%",
  },
  dateRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 1,
  },
  dateText: {
    fontSize: 8.5,
    textAlign: "right",
    fontWeight: "medium",
  },
  row: {
    flexDirection: "row",
    marginBottom: 4,
    alignItems: "center",
  },
  input: {
    borderBottom: "0.5 solid #2E7D32",
    flex: 1,
    marginLeft: 4,
    fontSize: 8.5,
    paddingBottom: 1,
  },
  mainText: {
    fontSize: 8.5,
    marginVertical: 6,
    lineHeight: 1.3,
  },
  label: {
    fontSize: 8,
    color: "#2E7D32",
    fontWeight: "medium",
  },
  smallText: {
    fontSize: 7,
    color: "#424242",
    marginBottom: 4,
    lineHeight: 1.2,
  },
  debtorInfo: {
    border: "0.5 solid #2E7D32",
    padding: 5,
    marginTop: 4,
    borderRadius: 3,
    backgroundColor: "#F9FBF7",
  },
  signature: {
    alignItems: "center",
    marginTop: 6,
    marginBottom: 4,
    fontSize: 8,
  },
  twoLineContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 6,
    marginTop: 3,
  },
  lineContainer: {
    flex: 1,
    marginHorizontal: 3,
  },
  lineText: {
    fontSize: 8.5,
    borderBottom: "0.5 solid #2E7D32",
    paddingBottom: 2,
    fontWeight: "medium",
  },
  lineLabel: {
    fontSize: 7.5,
    color: "#2E7D32",
    marginTop: 1,
  },
  guarantorInfo: {
    border: "0.5 solid #2E7D32",
    padding: 5,
    marginTop: 6,
    borderRadius: 3,
    backgroundColor: "#F9FBF7",
  },
  guarantorTitle: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: "#2E7D32",
    marginBottom: 3,
  },
  inlineRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
    alignItems: "center",
  },
  inlineLabel: {
    fontSize: 7.5,
    color: "#2E7D32",
    fontWeight: "medium",
  },
  inlineInput: {
    borderBottom: "0.5 solid #2E7D32",
    flex: 1,
    marginLeft: 3,
    fontSize: 8,
    paddingBottom: 1,
  },
  guarantorSignature: {
    marginTop: 10,
    paddingTop: 4,
  },
  guarantorSignatureText: {
    fontSize: 8,
    color: "#2E7D32",
    textAlign: "center",
    marginBottom: 3,
  },
  combinedRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
    alignItems: "center",
  },
  addressInput: {
    borderBottom: "0.5 solid #2E7D32",
    flex: 2,
    marginLeft: 3,
    marginRight: 8,
    fontSize: 8.5,
    paddingBottom: 1,
  },
  cityInput: {
    borderBottom: "0.5 solid #2E7D32",
    flex: 1,
    marginLeft: 3,
    fontSize: 8.5,
    paddingBottom: 1,
  },
  signatureLine: {
    borderTop: "0.75 solid #2E7D32",
    width: "70%",
    marginTop: 12,
    marginBottom: 3,
    alignSelf: "center",
  },
  signatureText: {
    fontSize: 8,
    textAlign: "center",
    color: "#2E7D32",
  },
  sectionDivider: {
    borderTop: "0.5 dashed #2E7D32",
    marginVertical: 4,
  },
  noteAmountHighlight: {
    fontWeight: "bold",
    color: "#2E7D32",
  },
  documentTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#2E7D32",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  documentNumber: {
    fontSize: 9,
    fontWeight: "medium",
    color: "#2E7D32",
  },
  footerNote: {
    fontSize: 6.5,
    color: "#757575",
    textAlign: "center",
    marginTop: 2,
  },
});
